# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agents/planner/planner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agents/planner/planner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61gents/planner/planner.proto\x12\x07planner\"\x1d\n\x0bPlanRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1b\n\x0cPlanResponse\x12\x0b\n\x03\x64\x61g\x18\x01 \x01(\t2@\n\x07Planner\x12\x35\n\x04Plan\x12\x14.planner.PlanRequest\x1a\x15.planner.PlanResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents.planner.planner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANREQUEST']._serialized_start=41
  _globals['_PLANREQUEST']._serialized_end=70
  _globals['_PLANRESPONSE']._serialized_start=72
  _globals['_PLANRESPONSE']._serialized_end=99
  _globals['_PLANNER']._serialized_start=101
  _globals['_PLANNER']._serialized_end=165
# @@protoc_insertion_point(module_scope)
